# 1.

# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
# # Find the sum of all the multiples of 3 or 5 below 1000.

# sum = 0
# for i in range(1, 1000):
# 	if i % 3 == 0 or i % 5 == 0:
# 		sum += i

# print(sum)

# The sum is 233168


# 2.

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# a = 1
# b = 2
# for i in range(1, 10):
# 		c = a + b
# 		a = b
# 		b = c

# if i % 2 == 0:
# 	print (a) 

# 3.

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?






